file_format: "1"
id: tracktyl
name: tracktyl
type: shield
url: https://github.com/b4nn4n4
requires:
  - pro_micro
exposes:
features:
  - keys
  - pointer
siblings:
  - tracktyl_left
  - tracktyl_right