manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/fliano
    - name: pmw3610
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: underglow-status-current-zmk-master
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: pmw3610
      revision: zmk-0.3
  self:
    path: config
