file_format: "1"
id: trancyglow
name: trancyglow
type: shield
url: https://github.com/fliano
requires:
  - pro_micro
exposes:
features:
  - keys
  - pointer
siblings:
  - trancyglow_left
  - trancyglow_right
